command_timeout = 250

[character]
success_symbol = "[âˆ´](bold green)"
error_symbol = "[âœ—](bold red)"

[package]
disabled = true

[git_branch]
style = "bold yellow"

[git_metrics]
disabled = false
format = '[+$added]($added_style)/[-$deleted]($deleted_style) '
deleted_style = "bold purple"

[git_status]
ahead = "â‡¡${count}"
diverged = "â‡•â‡¡${ahead_count}â‡£${behind_count}"
behind = "â‡£${count}"

[elixir]
style = "bold blue"

[cmd_duration]
style = "inverted bold yellow"
min_time = 2_000
show_milliseconds = true

[sudo]
disabled = false
style = "bold green"

[line_break]
disabled = false

[hostname]
ssh_only = false
trim_at = ""
style = "green bold"

[username]
show_always = true
format = "[$user]($style)@"
style_user = "yellow bold"

[directory]
truncation_length = 1
truncation_symbol = ""
repo_root_style = "bold red"
fish_style_pwd_dir_length = 1

[[battery.display]]
threshold = 85

[time]
disabled = false
format = 'ğŸ•¯ï¸ [$time]($style) '
time_format = "%T"
time_range = "21:00:00-07:00:00"
